spring.application.name=climber-tracker

spring.datasource.url=jdbc:postgresql://localhost:5432/climbing_tracker
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.application.name=climbing-tracker

server.port=${PORT:8080}